Repository Knox-AAU/DatabaseLayer_DocumentDataAPI, pull requests merged in 2022-10, with the labels that each got.

#1 Feature/setup api and data access
  DocumentDataAPI/DocumentDataAPI.sln
  DocumentDataAPI/DocumentDataAPI/Controllers/WeatherForecastController.cs
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/DatabaseDeployHelper.cs
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/deploy_schema.sql
  DocumentDataAPI/DocumentDataAPI/DocumentDataAPI.csproj
  DocumentDataAPI/DocumentDataAPI/Models/WeatherForecast.cs
  DocumentDataAPI/DocumentDataAPI/Options/DatabaseOptions.cs
  DocumentDataAPI/DocumentDataAPI/Program.cs
  DocumentDataAPI/DocumentDataAPI/Properties/launchSettings.json
  DocumentDataAPI/DocumentDataAPI/appsettings.Development.json
  DocumentDataAPI/DocumentDataAPI/appsettings.json
  DocumentDataAPI/DocumentDataAPITests/DocumentDataAPITests.csproj
  DocumentDataAPI/DocumentDataAPITests/Usings.cs
Labels: enhancement

#5 Models have been moved from the old wordcount repo.
  .github/linters/.sqlfluff
  DocumentDataAPI/DocumentDataAPI/Models/DocumentContentModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/DocumentModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/SourceModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/WordRatioModel.cs
Labels: enhancement

#7 Added populate_schema script and refactored DatabaseDeployHelper
  .gitignore
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/DatabaseDeployHelper.cs
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/Scripts/deploy_schema.sql
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/Scripts/populate_tables.sql
  DocumentDataAPI/DocumentDataAPI/Data/IDbConnectionFactory.cs
  DocumentDataAPI/DocumentDataAPI/Data/PostgresDbConnectionFactory.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/SourceRepository.cs
  DocumentDataAPI/DocumentDataAPI/DocumentDataAPI.csproj
  DocumentDataAPI/DocumentDataAPI/Program.cs
  DocumentDataAPI/DocumentDataAPI/Properties/launchSettings.json
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/SourceRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/DocumentDataAPITests.csproj
  DocumentDataAPI/DocumentDataAPITests/TestHelper.cs
  DocumentDataAPI/DocumentDataAPITests/Usings.cs
Labels: enhancement

#8 Database models
  .github/linters/.sqlfluff
  .github/workflows/linter.yaml
  DocumentDataAPI/DocumentDataAPI/Controllers/SourceController.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/DocumentContentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/DocumentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/ISourceRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/SourceRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/WordRatioRepository.cs
  DocumentDataAPI/DocumentDataAPI/Models/DocumentModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/WordRatioModel.cs
  DocumentDataAPI/DocumentDataAPI/Program.cs
Labels: enhancement

#10 Add primary key to document_contents table
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/Scripts/deploy_schema.sql
Labels: bug

#11 Feature/document contents controller
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentContentController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/SourceController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/WeatherForecastController.cs
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/DatabaseDeployHelper.cs
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/Scripts/deploy_schema.sql
  DocumentDataAPI/DocumentDataAPI/Data/Mappers/DocumentContentMap.cs
  DocumentDataAPI/DocumentDataAPI/Data/Mappers/DocumentMap.cs
  DocumentDataAPI/DocumentDataAPI/Data/Mappers/SourceMap.cs
  DocumentDataAPI/DocumentDataAPI/Data/Mappers/WordRatioMap.cs
  DocumentDataAPI/DocumentDataAPI/Data/NpgDbConnectionFactory.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/ISourceRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgDocumentContentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgDocumentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgSourceRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgWordRatioRepository.cs
  DocumentDataAPI/DocumentDataAPI/DocumentDataAPI.csproj
  DocumentDataAPI/DocumentDataAPI/Models/DocumentContentModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/DocumentModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/Rank.cs
  DocumentDataAPI/DocumentDataAPI/Models/SourceModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/WeatherForecast.cs
  DocumentDataAPI/DocumentDataAPI/Models/WordRatioModel.cs
  DocumentDataAPI/DocumentDataAPI/Program.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgSourceRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/TestHelper.cs
Labels: enhancement

#14 Include XML comments in swagger documentation, yea baby!
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentContentController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/RoutePrefixHelper.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/SourceController.cs
  DocumentDataAPI/DocumentDataAPI/DocumentDataAPI.csproj
  DocumentDataAPI/DocumentDataAPI/Program.cs
Labels: documentation

#19 Feature/change put methods
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentContentController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/WordRatioController.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/Helpers/DapperSqlHelper.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/Helpers/ISqlHelper.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IDocumentContentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IWordRatioRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgDocumentContentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgWordRatioRepository.cs
  DocumentDataAPI/DocumentDataAPI/Models/DocumentContentModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/DocumentModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/SourceModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/WordRatioModel.cs
  DocumentDataAPI/DocumentDataAPI/Program.cs
  DocumentDataAPI/DocumentDataAPI/RoutePrefixHelper.cs
  DocumentDataAPI/DocumentDataAPI/appsettings.json
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgDocumentContentRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgWordRatioRepositoryIntegrationTests.cs
Labels: enhancement

#21 Feature/documents controller
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentController.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IDocumentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgDocumentContentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgDocumentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgSourceRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgWordRatioRepository.cs
  DocumentDataAPI/DocumentDataAPI/Exceptions/RowsAffectedMismatchException.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgDocumentContentRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgDocumentRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgSourceRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/Usings.cs
Labels: enhancement

#22 Updated PUT endpoint on DocumentController for batch inserts
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentController.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IDocumentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgDocumentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Models/DocumentModel.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgDocumentRepositoryIntegrationTests.cs
Labels: enhancement

#23 Added DocumentSearchParameters to DocumentController GetAll and remov…
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentController.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IDocumentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgDocumentRepository.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgDocumentRepositoryIntegrationTests.cs
Labels: enhancement

#25 Rewrote API to be asynchronous
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentContentController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/SourceController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/WordRatioController.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IDocumentContentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IDocumentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/ISourceRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IWordRatioRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgDocumentContentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgDocumentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgSourceRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgWordRatioRepository.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgDocumentContentRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgDocumentRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgSourceRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgWordRatioRepositoryIntegrationTests.cs
Labels: enhancement

#27 added build.yaml action
  .github/workflows/build.yaml
  DocumentDataAPI/DocumentDataAPITests/DocumentDataAPITests.csproj
  DocumentDataAPI/DocumentDataAPITests/TestHelper.cs
Labels: enhancement

#28 Implemented POST and DELETE endpoints for the DocumentController
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentContentController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentController.cs
Labels: enhancement

#30 Create publish.yml
  .github/workflows/publish.yml
Labels: enhancement

#31 Create dockerfile
  DocumentDataAPI/DocumentDataAPI/.dockerignore
  DocumentDataAPI/DocumentDataAPI/Dockerfile
Labels: enhancement

#32 Release/1.0.0
  .github/linters/.sqlfluff
  .github/workflows/build.yaml
  .github/workflows/linter.yaml
  .gitignore
  DocumentDataAPI/DocumentDataAPI.sln
  DocumentDataAPI/DocumentDataAPI/.dockerignore
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentContentController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/SourceController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/WordRatioController.cs
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/DatabaseDeployHelper.cs
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/Scripts/deploy_schema.sql
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/Scripts/populate_tables.sql
  DocumentDataAPI/DocumentDataAPI/Data/IDbConnectionFactory.cs
  DocumentDataAPI/DocumentDataAPI/Data/Mappers/CategoryMap.cs
  DocumentDataAPI/DocumentDataAPI/Data/Mappers/DocumentContentMap.cs
  DocumentDataAPI/DocumentDataAPI/Data/Mappers/DocumentMap.cs
  DocumentDataAPI/DocumentDataAPI/Data/Mappers/SimilarDocumentMap.cs
  DocumentDataAPI/DocumentDataAPI/Data/Mappers/SourceMap.cs
  DocumentDataAPI/DocumentDataAPI/Data/Mappers/WordRatioMap.cs
  DocumentDataAPI/DocumentDataAPI/Data/NpgDbConnectionFactory.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/Helpers/DapperSqlHelper.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/Helpers/ISqlHelper.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IDocumentContentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IDocumentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/ISourceRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/IWordRatioRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgDocumentContentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgDocumentRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgSourceRepository.cs
  DocumentDataAPI/DocumentDataAPI/Data/Repositories/NpgWordRatioRepository.cs
  DocumentDataAPI/DocumentDataAPI/Dockerfile
  DocumentDataAPI/DocumentDataAPI/DocumentDataAPI.csproj
  DocumentDataAPI/DocumentDataAPI/Exceptions/RowsAffectedMismatchException.cs
  DocumentDataAPI/DocumentDataAPI/Models/CategoryModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/DocumentContentModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/DocumentModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/DocumentSearchParameters.cs
  DocumentDataAPI/DocumentDataAPI/Models/ISearchParameters.cs
  DocumentDataAPI/DocumentDataAPI/Models/QueryParameter.cs
  DocumentDataAPI/DocumentDataAPI/Models/Rank.cs
  DocumentDataAPI/DocumentDataAPI/Models/SimilarDocumentModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/SourceModel.cs
  DocumentDataAPI/DocumentDataAPI/Models/WordRatioModel.cs
  DocumentDataAPI/DocumentDataAPI/Options/DatabaseOptions.cs
  DocumentDataAPI/DocumentDataAPI/Program.cs
  DocumentDataAPI/DocumentDataAPI/Properties/launchSettings.json
  DocumentDataAPI/DocumentDataAPI/RoutePrefixHelper.cs
  DocumentDataAPI/DocumentDataAPI/appsettings.Development.json
  DocumentDataAPI/DocumentDataAPI/appsettings.json
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgDocumentContentRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgDocumentRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgSourceRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/Data/Repositories/NpgWordRatioRepositoryIntegrationTests.cs
  DocumentDataAPI/DocumentDataAPITests/DocumentDataAPITests.csproj
  DocumentDataAPI/DocumentDataAPITests/TestHelper.cs
  DocumentDataAPI/DocumentDataAPITests/Usings.cs
  README.md
Labels: good first issue

#39 Configured Dapper mappers and added database users to deploy_schema.sql
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/Scripts/deploy_schema.sql
  DocumentDataAPI/DocumentDataAPI/Program.cs
  DocumentDataAPI/DocumentDataAPITests/TestHelper.cs
Labels: enhancement

#40 Add indices in deploy_schema.sql
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/Scripts/deploy_schema.sql
Labels: enhancement

#41 Minor db user fixes (privileges)
  DocumentDataAPI/DocumentDataAPI/Data/Deployment/Scripts/deploy_schema.sql
Labels: bug

#43 Swap put and post endpoints
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentContentController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/DocumentController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/SourceController.cs
  DocumentDataAPI/DocumentDataAPI/Controllers/WordRatioController.cs
  DocumentDataAPI/DocumentDataAPI/Models/DocumentContentModel.cs
Labels: documentation
